import React from 'react'

const Terms = () => {
    return (
        <div className="terms-container">
            <div className="terms-header">
                <div className="heading">
                    Terms and conditions
                </div>
                <div className="desc">THese should guide you</div>
            </div>
            <div className="divider-line"></div>
            <div className="vertical-right-line"></div>

            <div className="terms-content-wrapper">
                <div className="terms-intro">
                    <p>
                        The Seven22 Project is a collection of digital artworks (NFTs) running on the Ethereum network. This website is only an interface allowing participants to exchange digital collectibles. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. Furthermore, as The Seven22 Project smart contract runs on the Ethereum network, there is not ability to undo, reverse, or restore any transactions.
                    </p>
                    <p>This website and its connected services are provided “as is” and “as available” without warranty of any kind. By using this website you are accepting sole responsibility for any and all transactions involving The Seven22 Project digital collectibles.</p>
                </div>

                <div className="terms-points">
                    <div className="point-heading">
                        i. Ownership
                    </div>
                    <div className="point-desc">
                        You Own the NFT. Each HDN FIGRZ Collectable is an NFT on the Ethereum blockchain. When you purchase an NFT, you own the underlying HDN FIGRZ Collectable and the art. Ownership of the NFT is mediated entirely by the Smart Contract and the Ethereum Network: at no point may we seize, freeze, or otherwise modify the ownership of any HDN FIGRZ Collectable.
                    </div>
                </div>
                <div className="terms-points">
                    <div className="point-heading">
                        ii. Personal Use.
                    </div>
                    <div className="point-desc">
                        Subject to your continued compliance with these Terms, WSX, LLC grants you a worldwide, royalty-free license to use, copy, and display the purchased NFT, along with any extensions that you choose to create or use, solely for the following purposes: (i) for your own personal, non-commercial use; (ii) as part of a marketplace the permits the purchase and sale of your HDN FIGRZ Collectable/ NFT, provided that the marketplace cryptographically verifies each HDN FIGRZ Collectable owner’s rights to display the art for their HDN FIGRZ Collectable to ensure that only the actual owner can display the art; or (iii) as part of a third party website or application that permits the inclusion, involvement, or participation of your HDN FIGRZ Collectable, provided that the website/application cryptographically verifies each HDN FIGRZ Collectable owner’s rights to display the Art for their HDN FIGRZ Collectable to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the HDN FIGRZ Collectable leaves the website/application.
                    </div>
                </div>
                <div className="terms-points">
                    <div className="point-heading">
                        iii. Commercial Use
                    </div>
                    <div className="point-desc">
                        . Subject to your continued compliance with these Terms, WSX, LLC grants you an unlimited, worldwide license to use, copy, and display the purchased Art for the purpose of creating derivative works based upon the Art (“Commercial Use”). Examples of such Commercial Use would e.g. be the use of the Art to produce and sell merchandise products (T-shirts etc.) displaying copies of the Art. For the sake of clarity, nothing in this Section will be deemed to restrict you from (i) owning or operating a marketplace that permits the use and sale of HDN FIGRZ Collectable generally, provided that the marketplace cryptographically verifies each HDN FIGRZ Collectable owner’s rights to display the Art for their HDN FIGRZ Collectable to ensure that only the actual owner can display the Art; (iii) owning or operating a third party website or application that permits the inclusion, involvement, or participation of Seven22 generally, provided that the third party website or application cryptographically verifies each HDN FIGRZ Collectable owner’s rights to display the Art, and provided that the Art is no longer visible once the owner of the Purchased HDN FIGRZ Collectable leaves the website/application; or (iii) earning revenue from any of the foregoing.
                    </div>
                </div>
            </div>

        </div>
    )
}

export default Terms;